INSERT INTO tb_exercises (exercise_id, name, intensity, difficulty) VALUES
(1, 'Running', 'HIGH', 'INTERMEDIATE'),
(2, 'Barbell Squat', 'HIGH', 'INTERMEDIATE'),
(3, 'Push-up', 'MEDIUM', 'BEGINNER'),
(4, 'Deadlift', 'HIGH', 'EXPERIENCED'),
(5, 'Jump Rope', 'HIGH', 'BEGINNER'),
(6, 'Front Pulldown', 'MEDIUM', 'INTERMEDIATE'),
(7, 'Burpee', 'HIGH', 'INTERMEDIATE'),
(8, 'Hamstring Stretch', 'LOW', 'BEGINNER'),
(9, 'Bench Press', 'HIGH', 'INTERMEDIATE'),
(10, 'Abdominal Crunch', 'MEDIUM', 'BEGINNER'),
(11, 'Calf Raise', 'MEDIUM', 'BEGINNER'),
(12, 'Bent-over Row', 'MEDIUM', 'INTERMEDIATE'),
(13, 'Shoulder Press', 'HIGH', 'INTERMEDIATE'),
(14, 'Lunge', 'HIGH', 'INTERMEDIATE'),
(15, 'Bicep Curl', 'MEDIUM', 'BEGINNER'),
(16, 'Incline Push-up', 'LOW', 'BEGINNER'),
(17, 'Stiff-legged Deadlift', 'HIGH', 'INTERMEDIATE'),
(18, 'Alternating Bicep Curl', 'MEDIUM', 'BEGINNER'),
(19, 'Triceps Skull Crusher', 'MEDIUM', 'INTERMEDIATE'),
(20, 'Leg Extension', 'HIGH', 'INTERMEDIATE'),
(21, 'Lateral Raise', 'MEDIUM', 'BEGINNER'),
(22, 'Smith Machine Lunge', 'HIGH', 'EXPERIENCED'),
(23, 'Chest Fly', 'MEDIUM', 'BEGINNER'),
(24, 'Adductor Machine', 'HIGH', 'BEGINNER'),
(25, 'Shoulder Shrug', 'MEDIUM', 'INTERMEDIATE'),
(26, 'Seated Calf Raise', 'HIGH', 'BEGINNER'),
(27, 'Swiss Ball Crunch', 'MEDIUM', 'INTERMEDIATE'),
(28, 'Low Row', 'MEDIUM', 'BEGINNER'),
(29, 'Triceps Rope Extension', 'MEDIUM', 'INTERMEDIATE'),
(30, 'Front Raise', 'MEDIUM', 'BEGINNER'),
(31, 'Hanging Leg Raise', 'LOW', 'BEGINNER'),
(32, 'Leg Curl Machine', 'HIGH', 'BEGINNER'),
(33, 'Scott Curl', 'MEDIUM', 'BEGINNER'),
(34, 'Dip', 'HIGH', 'INTERMEDIATE'),
(35, 'Machine Crunch', 'MEDIUM', 'BEGINNER'),
(36, 'Triceps Pulldown', 'MEDIUM', 'INTERMEDIATE'),
(37, 'Heel Raise', 'LOW', 'BEGINNER'),
(38, 'Reverse Fly', 'MEDIUM', 'INTERMEDIATE'),
(39, 'Abductor Machine', 'HIGH', 'BEGINNER'),
(40, 'Wrist Curl', 'MEDIUM', 'BEGINNER'),
(41, 'Leg Curl', 'HIGH', 'BEGINNER'),
(42, 'Ball Crunch', 'MEDIUM', 'BEGINNER'),
(43, 'Neutral Grip Pulldown', 'HIGH', 'INTERMEDIATE'),
(44, 'Triceps Kickback', 'MEDIUM', 'INTERMEDIATE'),
(45, 'Hack Squat', 'HIGH', 'EXPERIENCED'),
(46, 'Quadriceps Stretch', 'LOW', 'BEGINNER'),
(47, 'Calf Stretch', 'LOW', 'BEGINNER'),
(48, 'Shoulder Stretch', 'LOW', 'BEGINNER'),
(49, 'Spinal Twist', 'LOW', 'BEGINNER');


INSERT INTO tb_muscles (exercise_model_exercise_id, muscles) VALUES
(1, 'QUADRICEPS'),
(1, 'CALF'),
(1, 'GLUTES'),
(2, 'QUADRICEPS'),
(2, 'GLUTES'),
(2, 'LOWER_BACK'),
(3, 'CHEST'),
(3, 'TRICEPS'),
(3, 'DELTOIDS'),
(4, 'LOWER_BACK'),
(4, 'GLUTES'),
(4, 'QUADRICEPS'),
(5, 'CALF'),
(5, 'QUADRICEPS'),
(5, 'GLUTES'),
(6, 'BACK'),
(6, 'BICEPS'),
(6, 'DELTOIDS'),
(7, 'QUADRICEPS'),
(7, 'GLUTES'),
(7, 'CHEST'),
(8, 'HAMSTRINGS'),
(9, 'CHEST'),
(9, 'TRICEPS'),
(9, 'DELTOIDS'),
(10, 'ABDOMEN'),
(11, 'CALF'),
(12, 'BACK'),
(12, 'BICEPS'),
(12, 'LOWER_BACK'),
(13, 'DELTOIDS'),
(13, 'TRICEPS'),
(14, 'QUADRICEPS'),
(14, 'GLUTES'),
(14, 'HAMSTRINGS'),
(15, 'BICEPS'),
(15, 'FOREARM'),
(16, 'CHEST'),
(16, 'TRICEPS'),
(16, 'DELTOIDS'),
(17, 'HAMSTRINGS'),
(17, 'LOWER_BACK'),
(18, 'BICEPS'),
(18, 'FOREARM'),
(19, 'TRICEPS'),
(20, 'QUADRICEPS'),
(21, 'DELTOIDS'),
(22, 'QUADRICEPS'),
(22, 'GLUTES'),
(22, 'HAMSTRINGS'),
(23, 'CHEST'),
(24, 'ADDUCTORS'),
(25, 'TRAPEZIUS'),
(26, 'CALF'),
(27, 'ABDOMEN'),
(28, 'BACK'),
(29, 'TRICEPS'),
(30, 'DELTOIDS'),
(31, 'ABDOMEN'),
(32, 'HAMSTRINGS'),
(33, 'BICEPS'),
(34, 'CHEST'),
(34, 'TRICEPS'),
(35, 'ABDOMEN'),
(36, 'TRICEPS'),
(37, 'CALF'),
(38, 'DELTOIDS'),
(39, 'ADDUCTORS'),
(40, 'FOREARM'),
(41, 'HAMSTRINGS'),
(42, 'ABDOMEN'),
(43, 'BACK'),
(43, 'BICEPS'),
(44, 'TRICEPS'),
(45, 'QUADRICEPS'),
(45, 'GLUTES'),
(45, 'HAMSTRINGS'),
(46, 'QUADRICEPS'),
(47, 'CALF'),
(48, 'DELTOIDS'),
(49, 'LOWER_BACK');
