INSERT INTO EXERCISE (exercise_id, name, intensity, exercise_type, difficulty) VALUES
(1, 'Corrida', 'ALTA', 'CARDIO', 'INTERMEDIARIO'),
(2, 'Agachamento com barra', 'ALTA', 'LEVANTAMENTO_PESO', 'INTERMEDIARIO'),
(3, 'Flexão de braço', 'MEDIA', 'FORCA', 'INICIANTE'),
(4, 'Levantamento terra', 'ALTA', 'LEVANTAMENTO_PESO_OLIMPICO', 'EXPERIENTE'),
(5, 'Pular corda', 'ALTA', 'CARDIO', 'INICIANTE'),
(6, 'Puxada frontal', 'MEDIA', 'FORCA', 'INTERMEDIARIO'),
(7, 'Burpee', 'ALTA', 'PLIOMETRIA', 'INTERMEDIARIO'),
(8, 'Alongamento de isquiotibiais', 'BAIXA', 'ALONGAMENTO', 'INICIANTE'),
(9, 'Supino reto', 'ALTA', 'LEVANTAMENTO_PESO', 'INTERMEDIARIO'),
(10, 'Abdominal crunch', 'MEDIA', 'FORCA', 'INICIANTE'),
(11, 'Elevação de panturrilha', 'MEDIA', 'FORCA', 'INICIANTE'),
(12, 'Remada curvada', 'MEDIA', 'FORCA', 'INTERMEDIARIO'),
(13, 'Desenvolvimento de ombro', 'ALTA', 'LEVANTAMENTO_PESO', 'INTERMEDIARIO'),
(14, 'Afundo', 'ALTA', 'LEVANTAMENTO_PESO', 'INTERMEDIARIO'),
(15, 'Rosca direta', 'MEDIA', 'FORCA', 'INICIANTE'),
(16, 'Flexão de braço inclinada', 'BAIXA', 'FORCA', 'INICIANTE'),
(17, 'Stiff', 'ALTA', 'LEVANTAMENTO_PESO', 'INTERMEDIARIO'),
(18, 'Rosca alternada', 'MEDIA', 'FORCA', 'INICIANTE'),
(19, 'Tríceps testa', 'MEDIA', 'FORCA', 'INTERMEDIARIO'),
(20, 'Cadeira extensora', 'ALTA', 'LEVANTAMENTO_PESO', 'INTERMEDIARIO'),
(21, 'Elevação lateral', 'MEDIA', 'FORCA', 'INICIANTE'),
(22, 'Afundo no Smith', 'ALTA', 'LEVANTAMENTO_PESO', 'EXPERIENTE'),
(23, 'Crucifixo', 'MEDIA', 'FORCA', 'INICIANTE'),
(24, 'Máquina adutora', 'ALTA', 'LEVANTAMENTO_PESO', 'INICIANTE'),
(25, 'Encolhimento de ombros', 'MEDIA', 'FORCA', 'INTERMEDIARIO'),
(26, 'Gêmeos sentado', 'ALTA', 'LEVANTAMENTO_PESO', 'INICIANTE'),
(27, 'Crunch com bola', 'MEDIA', 'FORCA', 'INTERMEDIARIO'),
(28, 'Remada baixa', 'MEDIA', 'FORCA', 'INICIANTE'),
(29, 'Extensão de tríceps com corda', 'MEDIA', 'FORCA', 'INTERMEDIARIO'),
(30, 'Elevação frontal', 'MEDIA', 'FORCA', 'INICIANTE'),
(31, 'Elevação de pernas suspensa', 'BAIXA', 'FORCA', 'INICIANTE'),
(32, 'Máquina flexora', 'ALTA', 'LEVANTAMENTO_PESO', 'INICIANTE'),
(33, 'Rosca scott', 'MEDIA', 'FORCA', 'INICIANTE'),
(34, 'Mergulho', 'ALTA', 'FORCA', 'INTERMEDIARIO'),
(35, 'Crunch na máquina', 'MEDIA', 'FORCA', 'INICIANTE'),
(36, 'Tríceps na polia', 'MEDIA', 'FORCA', 'INTERMEDIARIO'),
(37, 'Elevação de calcanhares', 'BAIXA', 'FORCA', 'INICIANTE'),
(38, 'Voador inverso', 'MEDIA', 'FORCA', 'INTERMEDIARIO'),
(39, 'Máquina abdutora', 'ALTA', 'LEVANTAMENTO_PESO', 'INICIANTE'),
(40, 'Rosca punho', 'MEDIA', 'FORCA', 'INICIANTE'),
(41, 'Cadeira flexora', 'ALTA', 'LEVANTAMENTO_PESO', 'INICIANTE'),
(42, 'Crunch na bola', 'MEDIA', 'FORCA', 'INICIANTE'),
(43, 'Puxada neutra', 'ALTA', 'FORCA', 'INTERMEDIARIO'),
(44, 'Tríceps coice', 'MEDIA', 'FORCA', 'INTERMEDIARIO'),
(45, 'Agachamento hack', 'ALTA', 'LEVANTAMENTO_PESO', 'EXPERIENTE'),
(46, 'Alongamento de quadríceps', 'BAIXA', 'ALONGAMENTO', 'INICIANTE'),
(47, 'Alongamento de panturrilha', 'BAIXA', 'ALONGAMENTO', 'INICIANTE'),
(48, 'Alongamento de ombros', 'BAIXA', 'ALONGAMENTO', 'INICIANTE'),
(49, 'Torção da coluna vertebral', 'BAIXA', 'ALONGAMENTO', 'INICIANTE');
 -- Continue inserting other exercises

-- Inserting Muscle data
INSERT INTO MUSCLES (exercise_model_exercise_id, muscles) VALUES
(1, 'QUADRICEPS'),
(1, 'PANTURRILHA'),
(1, 'GLUTEOS'),
(2, 'QUADRICEPS'),
(2, 'GLUTEOS'),
(2, 'LOMBAR'),
(3, 'PEITORAL'),
(3, 'TRICEPS'),
(3, 'DELTOIDES'),
(4, 'LOMBAR'),
(4, 'GLUTEOS'),
(4, 'QUADRICEPS'),
(5, 'PANTURRILHA'),
(5, 'QUADRICEPS'),
(5, 'GLUTEOS'),
(6, 'DORSAL'),
(6, 'BICEPS'),
(6, 'DELTOIDES'),
(7, 'QUADRICEPS'),
(7, 'GLUTEOS'),
(7, 'PEITORAL'),
(8, 'ISQUIOTIBIAIS'),
(9, 'PEITORAL'),
(9, 'TRICEPS'),
(9, 'DELTOIDES'),
(10, 'ABDOMEN'),
(11, 'PANTURRILHA'),
(12, 'DORSAL'),
(12, 'BICEPS'),
(12, 'LOMBAR'),
(13, 'DELTOIDES'),
(13, 'TRICEPS'),
(14, 'QUADRICEPS'),
(14, 'GLUTEOS'),
(14, 'ISQUIOTIBIAIS'),
(15, 'BICEPS'),
(15, 'ANTEBRACO'),
(16, 'PEITORAL'),
(16, 'TRICEPS'),
(16, 'DELTOIDES'),
(17, 'ISQUIOTIBIAIS'),
(17, 'LOMBAR'),
(18, 'BICEPS'),
(18, 'ANTEBRACO'),
(19, 'TRICEPS'),
(20, 'QUADRICEPS'),
(21, 'DELTOIDES'),
(22, 'QUADRICEPS'),
(22, 'GLUTEOS'),
(22, 'ISQUIOTIBIAIS'),
(23, 'PEITORAL'),
(24, 'ADUTORES'),
(25, 'TRAPEZIO'),
(26, 'PANTURRILHA'),
(27, 'ABDOMEN'),
(28, 'DORSAL'),
(29, 'TRICEPS'),
(30, 'DELTOIDES'),
(31, 'ABDOMEN'),
(32, 'ISQUIOTIBIAIS'),
(33, 'BICEPS'),
(34, 'PEITORAL'),
(34, 'TRICEPS'),
(35, 'ABDOMEN'),
(36, 'TRICEPS'),
(37, 'PANTURRILHA'),
(38, 'DELTOIDES'),
(39, 'ADUTORES'),
(40, 'ANTEBRACO'),
(41, 'ISQUIOTIBIAIS'),
(42, 'ABDOMEN'),
(43, 'DORSAL'),
(43, 'BICEPS'),
(44, 'TRICEPS'),
(45, 'QUADRICEPS'),
(45, 'GLUTEOS'),
(45, 'ISQUIOTIBIAIS'),
(46, 'QUADRICEPS'),
(47, 'PANTURRILHA'),
(48, 'DELTOIDES'),
(49, 'LOMBAR');;